### ISSUE TITLE
gitlib-3.1.1 build fails with conduit-1.3

### ISSUE THREAD

**Issue by DanBurton** [jwiegley/gitlib#72]
Seen on the stackage build server; I was able to reproduce the build failure locally like so:

```bash
stack unpack gitlib-3.1.1 && cd gitlib-3.1.1
edit stack.yaml # add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- conduit-1.3.0
- conduit-extra-1.3.0
- resourcet-1.2.0
```

Build failure:

```
[15 of 15] Compiling Git.Working      ( Git/Working.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Git/Working.o )

/Users/dan/scratch/gitlib-3.1.1/Git/Working.hs:18:33: error:
    Not in scope: type constructor or class ‘MonadBaseControl’
   |
18 | checkoutFiles :: (MonadGit r m, MonadBaseControl IO m, MonadIO m,
   |                                 ^^^^^^^^^^^^^^^^
```
